name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}

    - uses: pnpm/action-setup@v4
      with:
        version: 10.29.3

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
        registry-url: https://registry.npmjs.org

    - run: pnpm install --frozen-lockfile

    - run: pnpm build

    - run: pnpm pack

    - run: gh release upload "${{ github.event.release.tag_name }}" ./*.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: pnpm publish --access public --provenance --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-demo:
    name: Deploy demo
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}

    - uses: pnpm/action-setup@v4
      with:
        version: 10.29.3

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - run: pnpm install --frozen-lockfile

    - run: pnpm build:demo

    - uses: actions/upload-pages-artifact@v4
      with:
        path: dist-demo

    - uses: actions/deploy-pages@v4
